title: Advanced configurations
abstract: A few hints to further configure your Pydio Cells server instance.
menu: Advanced configurations
language: und
weight: 7
menu_name: menu-admin-guide-v7-enterprise
