title: Configuring Cells URLs
abstract: This section provides information about managing multiple "sites" and additional information to configure Pydio Cells network configuration.
menu: Configuring URLs
language: und
weight: 4
menu_name: menu-administration-guide
